spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: Negociation-service
  server:
    port: 8083

---

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: MsChatSocketApplication
  server:
    port: 8082