server:
  port: 8222
spring:
  cloud:
    gateway:
      routes:
        - id: assurances-route
          uri: lb://ASSURANCE
          predicates:
            - Path=/api/assurance/**
        - id: pointages-route
          uri: lb://POINTAGE
          predicates:
            - Path=/api/pointage/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:4200"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600