server:
  port: 8222

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # Route for assurances
        - id: assurances-route
          uri: lb://ASSURANCE-SERVICE
          predicates:
            - Path=/api/assurances/**

        # Route for contrats
        - id: contrats-route
          uri: lb://ASSURANCE-SERVICE
          predicates:
            - Path=/api/contrats/**

        # Route for maintenances
        - id: maintenances-route
          uri: lb://ASSURANCE-SERVICE
          predicates:
            - Path=/api/maintenances/**

        # Route for projets
        - id: projets-route
          uri: lb://ASSURANCE-SERVICE
          predicates:
            - Path=/api/projets/**




#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowed-origins: "http://localhost:4200" # Allow requests from Angular app
#            allowed-methods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#              - OPTIONS
#            allowed-headers: "*"
#            allow-credentials: true
#            max-age: 3600 # Cache preflight response for 1 hour