
spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/user_service?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        enable_lazy_load_no_trans: true

  security:
    enabled: false
    oauth2:
      resourceserver:
        jwt:
          secret: "secretKey"
          issuer-uri: "http://localhost:8080/realms/User-service"
          jwk-set-uri: "http://localhost:8080/realms/User-service/protocol/openid-connect/certs"

  mail:
    host: smtp.gmail.com
    port: 587
    username: by.mehdi721@gmail.com
    password: mrdq hbom sxyc xmoi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

server:
  port: 8082

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


