spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
<<<<<<< HEAD
server:
  port: 8888
=======

server:
  port: 8888
>>>>>>> origin/user-services
